name: ✅ tests #and coverage

on: [push, pull_request]

jobs:
  tests:
    name: test with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11-dev"
          - "pypy-3.7"
          - "pypy-3.8"
          - "pypy-3.9"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd docutils
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install pygments
        # for recommonmark
        python -m pip install commonmark
        python -m pip install recommonmark --no-deps
        # for visual inspection
        python -m pip list

    - name: Run test suite
      run: |
        cd docutils/test
        python alltests.py
